version: "3.4"

services:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=12345
    volumes:
      - postgres:/var/lib/postgresql/data
      - ${PWD}/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

volumes:
  postgres:
